<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

return new class extends Migration
{
    /**
     * Run the migrations.
     */
    public function up(): void
    {
        // 1. Sales Order (Proses Pembayaran)
        Schema::create('sales_orders', function (Blueprint $table) {
            $table->id();
            $table->foreignId('boq_id')->constrained('boqs')->cascadeOnDelete();
            $table->string('so_number')->unique(); // Generated by Admin Sales
            $table->string('status')->default('draft'); // draft, submitted, approved, processing, paid

            // Files
            $table->string('po_spk_file')->nullable();
            $table->string('npwp_file')->nullable();
            $table->string('dp_invoice_file')->nullable();
            $table->string('dp_payment_proof')->nullable();

            // Approval
            $table->foreignId('approved_by')->nullable()->constrained('users');
            $table->timestamp('approved_at')->nullable();

            $table->text('notes')->nullable();
            $table->timestamps();
        });

        // 2. Delivery Order (Proses Pengiriman)
        Schema::create('delivery_orders', function (Blueprint $table) {
            $table->id();
            $table->foreignId('sales_order_id')->constrained('sales_orders')->cascadeOnDelete();
            $table->string('do_number')->nullable();
            $table->string('status')->default('pending'); // pending, processed, shipped, delivered

            // Files
            $table->string('invoice_file')->nullable(); // Invoice resmi
            $table->string('do_file_unsigned')->nullable(); // Surat jalan awal
            $table->string('do_file_signed')->nullable(); // Surat jalan ttd
            $table->string('checklist_file')->nullable();

            // Logistics
            $table->string('shipping_type')->default('internal'); // internal, external
            $table->date('schedule_date')->nullable();
            $table->string('courier_name')->nullable();
            $table->string('receipt_number')->nullable(); // Resi
            $table->json('photos')->nullable(); // Bukti barang sampai (array of paths)

            $table->text('notes')->nullable();
            $table->timestamps();
        });

        // 3. Installation (Proses Instalasi)
        Schema::create('installations', function (Blueprint $table) {
            $table->id();
            $table->foreignId('delivery_order_id')->constrained('delivery_orders')->cascadeOnDelete();

            $table->dateTime('schedule_date')->nullable();
            $table->string('technician_name')->nullable();
            $table->dateTime('finish_date')->nullable();
            $table->string('status')->default('pending'); // pending, scheduled, finished

            $table->string('proof_file')->nullable(); // BAST / Bukti pasang
            $table->text('notes')->nullable();
            $table->timestamps();
        });

        // 4. After Sales (Pelunasan & Garansi)
        // Linked to Sales Order (Finance flow) or Delivery (Operational flow). 
        // Following requirement "Proses After Sales" implies it happens after delivery/install.
        // We link it to Sales Order as it handles "Pelunasan" (Finance) and "Garansi".
        Schema::create('after_sales', function (Blueprint $table) {
            $table->id();
            $table->foreignId('sales_order_id')->constrained('sales_orders')->cascadeOnDelete();

            $table->string('status')->default('pending'); // pending, billed, paid, warranty_issued

            // Files
            $table->string('final_billing_file')->nullable(); // Tagihan pelunasan
            $table->string('payment_proof_file')->nullable(); // Bukti bayar pelunasan
            $table->string('warranty_letter_file')->nullable(); // Surat garansi

            // Approval
            $table->string('warranty_status')->default('draft'); // draft, approved
            $table->foreignId('approved_by')->nullable()->constrained('users');

            $table->text('notes')->nullable();
            $table->timestamps();
        });
    }

    /**
     * Reverse the migrations.
     */
    public function down(): void
    {
        Schema::dropIfExists('after_sales');
        Schema::dropIfExists('installations');
        Schema::dropIfExists('delivery_orders');
        Schema::dropIfExists('sales_orders');
    }
};
